#!/usr/bin/perl -w 

eval 'exec /usr/bin/perl -w  -S $0 ${1+"$@"}'
    if 0; # not running under some shell
use strict;

# pod docs at end.

BEGIN {
	$ENV{'CGL_CHATTER'} = 1;
}


$| = 1;
use Bio::SearchIO;
use Bio::Search::Hit::HitFactory;
use Bio::Search::HSP::HSPFactory;


my $usage = "

cgl_compare_annotations: 

a simple introduction to using the PhatHit and PhatHSP 
objects to compare annotations to one-another using a 
BLASTP report 

cgl_compare_annotations  <blastp report> <query chaos.xml document> <hit chaos.xml document>

XXXXXXXXXXXXXX this script needs to be completed!
\n"; 

#-----------------------------------------------------------------------------
#----------------------------------- MAIN ------------------------------------
#-----------------------------------------------------------------------------

die $usage unless $ARGV[2];

my $blast_report = $ARGV[0];
my $q_xml_doc    = $ARGV[1];
my $h_xml_doc    = $ARGV[2];


die "this script needs to be completed!\n";

my $sio = parseBlast($blast_report);

#-----------------------------------------------------------------------------
#---------------------------------- SUBS -------------------------------------
#-----------------------------------------------------------------------------
#-----------------------------------------------------------------------------
sub parseBlast {
        my $report = shift;

	my $hitType = 'Bio::Search::Hit::PhatHit::blastp';
	my $hspType = 'Bio::Search::HSP::PhatHSP::blastp';

        my $sio = new Bio::SearchIO(-format => 'blast',
                                    -file   => $report,
                                   );

        my $hspFactory = new Bio::Search::HSP::HSPFactory(-type =>$hspType);
        my $hitFactory = new Bio::Search::Hit::HitFactory(-type =>$hitType);


        $sio->_eventHandler->register_factory('hsp', $hspFactory);
        $sio->_eventHandler->register_factory('hit', $hitFactory);

        return $sio;
}
#-----------------------------------------------------------------------------

__END__

=head1 NAME

cgl_compare_annotations

=head1 SYNOPSIS

  cgl_compare_annotations  <blastp report> <query chaos.xml document> <hit chaos.xml document>


=head1 DESCRIPTION

A simple introduction to using the PhatHit and PhatHSP objects to
compare annotations to one-another using a BLASTP report.

=head1 DOCUMENTATION

L<http://www.yandell-lab.org/cgl>

=cut
