#!/usr/bin/perl
use strict;
use warnings;

use lib "$ENV{CGL_GFF_LIB}";

use Getopt::Long;
use CGL::Annotation;
use Dumper::XML::Game;


#-----------------------------------------------------------------------------
#----------------------------------- MAIN ------------------------------------
#-----------------------------------------------------------------------------
my $usage = "

Synopsis:

gff2game --format gff3_flybase --gff_file gff3_file [--fasta_file fasta_file]

Description:

This script will build a GAME XML file from associated gff and fasta
files. If no fasta file is give then it defaults to the name of the
gff3 file with the extension changed from gff or gff3 to fasta.

Options:

  --format  The format of the annotation GFF file

";

my ($help, $format);
my $opt_success = GetOptions('help'     => \$help,
			     'format=s' => \$format,
			      );

die $usage if $help || ! $opt_success;

my $gff3_file = shift;
my $fasta_file = shift;

if (! defined $fasta_file) {
	($fasta_file = $gff3_file) =~ s/gff3?$/fasta/;
}

die $usage unless $gff3_file && $fasta_file;

my $cgl = new CGL::Annotation->new(format     => $format,
				   gff_file   => $gff3_file,
				   fasta_file => $fasta_file)

my $game_io = new Dumper::XML::Game->init(Annot => $cgl);
$game_io->Game();
