#!/usr/bin/perl
use strict;
use warnings;

use lib "$ENV{CGL_GFF_LIB}";

use CGL::Annotation;
use Fasta;
use Shadower;
use PostData;
use Getopt::Long;

#-----------------------------------------------------------------------------
#----------------------------------- MAIN ------------------------------------
#-----------------------------------------------------------------------------

my $usage = "

Synopsis:

gff3_to_sens_spec --format gff3_flybase --gff_file <gff3 file> \
                           --fasta_file <fasta file>

Description:

??

";

my ($help, $format, $gff_file, $fasta_file);
my $opt_success = GetOptions('help'         => \$help,
			     'format=s'     => \$format,
			     'gff_file=s'   => \$gff_file,
			     'fasta_file=s' => \$fasta_file,
			     );

die $usage if $help;
die $usage unless $format && $gff3_file && $fasta_file;

my $cgl = CGL::Annotation->new(format     => $format,
			       gff_file   => $gff_file,
			       fasta_file => $fasta_file,
			      );

#Get Contig details
my $contig = $cgl->contig(0);
my $contig_id = $contig->id;

#Grab all the genes
my $genes = $cgl->genes;

my $exon_coors = get_exon_coors($cgl);

print_template($exon_coors, $cgl);

#-----------------------------------------------------------------------------
#------------------------------- SUBROUTINES ---------------------------------
#-----------------------------------------------------------------------------
sub print_template {
	my $coors = shift;
	my $cgl   = shift;

	my $contig = $cgl->contig(0);

	my $def = '>'.$contig->id();

	my $seq = $contig->residues();

	my $masked_seq = Shadower::maskSequence(\$seq, $coors, 0, '1');

	$$masked_seq =~ s/[^1]/0/g;

        my $m_fasta = Fasta::toFasta($def." gff3_sens_spec_template",
                                     $masked_seq,
                                    );


        print $$m_fasta;
}
#-----------------------------------------------------------------------------
sub get_exon_coors {
	my $cgl    = shift;

	my $genes = $cgl->genes();

	my @coors;
	for my $g (@{$genes}) {
        	my $i = 0;
        	while (my $t = $g->transcript($i)){
                	my $j = 0;
                	while (my $e = $t->exon($j)){
                        	my $nbeg = $e->nbeg();
                        	my $nend = $e->nend();

                        	push(@coors, [$nbeg, $nend]);

                        	$j++;
                	}
                	$i++;
        	}
	
	}

	return \@coors;
}
#-----------------------------------------------------------------------------

